version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"  # Map container port to localhost port
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"  # Map container port to localhost port
    environment:
      - MONGO_URI=mongodb+srv://admin:admin@cluster0.nugrie3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Map MongoDB port to localhost port
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
